
import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";
import { UserImage } from "../types";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generateTryOnImage = async (
  userImage: UserImage,
  productImage: UserImage,
  productName: string
): Promise<string> => {
  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: userImage.base64,
              mimeType: userImage.mimeType,
            },
          },
          {
            inlineData: {
              data: productImage.base64,
              mimeType: productImage.mimeType,
            },
          },
          {
            text: `This is a virtual try-on. Take the person from the first image and have them wear the "${productName}" from the second image. The clothing should fit them realistically. Generate a new, eye-catching, high-quality image of the person wearing the new outfit.`,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const firstPart = response.candidates?.[0]?.content?.parts?.[0];
    if (firstPart && firstPart.inlineData) {
      return firstPart.inlineData.data;
    } else {
      throw new Error('No image was generated by the API.');
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to generate image with Gemini API.");
  }
};
